export interface Country {
  code: string;   // ISO 3166-1 alpha-2
  name: string;
  dial: string;   // código de discagem sem "+"
  lang: string;   // idioma para a busca
}

export const COUNTRIES: Country[] = [
  { code: "BR", name: "Brasil", dial: "55", lang: "pt-BR" },
  { code: "PT", name: "Portugal", dial: "351", lang: "pt-PT" },
  { code: "AR", name: "Argentina", dial: "54", lang: "es" },
  { code: "CL", name: "Chile", dial: "56", lang: "es" },
  { code: "CO", name: "Colômbia", dial: "57", lang: "es" },
  { code: "MX", name: "México", dial: "52", lang: "es" },
  { code: "PE", name: "Peru", dial: "51", lang: "es" },
  { code: "UY", name: "Uruguai", dial: "598", lang: "es" },
  { code: "PY", name: "Paraguai", dial: "595", lang: "es" },
  { code: "BO", name: "Bolívia", dial: "591", lang: "es" },
  { code: "EC", name: "Equador", dial: "593", lang: "es" },
  { code: "VE", name: "Venezuela", dial: "58", lang: "es" },
  { code: "US", name: "Estados Unidos", dial: "1", lang: "en" },
  { code: "CA", name: "Canadá", dial: "1", lang: "en" },
  { code: "GB", name: "Reino Unido", dial: "44", lang: "en" },
  { code: "IE", name: "Irlanda", dial: "353", lang: "en" },
  { code: "AU", name: "Austrália", dial: "61", lang: "en" },
  { code: "NZ", name: "Nova Zelândia", dial: "64", lang: "en" },
  { code: "ES", name: "Espanha", dial: "34", lang: "es" },
  { code: "FR", name: "França", dial: "33", lang: "fr" },
  { code: "IT", name: "Itália", dial: "39", lang: "it" },
  { code: "DE", name: "Alemanha", dial: "49", lang: "de" },
  { code: "NL", name: "Holanda", dial: "31", lang: "nl" },
  { code: "BE", name: "Bélgica", dial: "32", lang: "fr" },
  { code: "CH", name: "Suíça", dial: "41", lang: "de" },
  { code: "AT", name: "Áustria", dial: "43", lang: "de" },
  { code: "SE", name: "Suécia", dial: "46", lang: "sv" },
  { code: "NO", name: "Noruega", dial: "47", lang: "no" },
  { code: "DK", name: "Dinamarca", dial: "45", lang: "da" },
  { code: "FI", name: "Finlândia", dial: "358", lang: "fi" },
  { code: "PL", name: "Polônia", dial: "48", lang: "pl" },
  { code: "CZ", name: "Tchéquia", dial: "420", lang: "cs" },
  { code: "GR", name: "Grécia", dial: "30", lang: "el" },
  { code: "TR", name: "Turquia", dial: "90", lang: "tr" },
  { code: "RO", name: "Romênia", dial: "40", lang: "ro" },
  { code: "HU", name: "Hungria", dial: "36", lang: "hu" },
  { code: "AO", name: "Angola", dial: "244", lang: "pt-PT" },
  { code: "MZ", name: "Moçambique", dial: "258", lang: "pt-PT" },
  { code: "CV", name: "Cabo Verde", dial: "238", lang: "pt-PT" },
  { code: "ZA", name: "África do Sul", dial: "27", lang: "en" },
  { code: "NG", name: "Nigéria", dial: "234", lang: "en" },
  { code: "KE", name: "Quênia", dial: "254", lang: "en" },
  { code: "EG", name: "Egito", dial: "20", lang: "ar" },
  { code: "MA", name: "Marrocos", dial: "212", lang: "fr" },
  { code: "AE", name: "Emirados Árabes", dial: "971", lang: "en" },
  { code: "SA", name: "Arábia Saudita", dial: "966", lang: "ar" },
  { code: "IL", name: "Israel", dial: "972", lang: "he" },
  { code: "IN", name: "Índia", dial: "91", lang: "en" },
  { code: "PK", name: "Paquistão", dial: "92", lang: "en" },
  { code: "BD", name: "Bangladesh", dial: "880", lang: "en" },
  { code: "ID", name: "Indonésia", dial: "62", lang: "id" },
  { code: "MY", name: "Malásia", dial: "60", lang: "en" },
  { code: "SG", name: "Singapura", dial: "65", lang: "en" },
  { code: "TH", name: "Tailândia", dial: "66", lang: "th" },
  { code: "VN", name: "Vietnã", dial: "84", lang: "vi" },
  { code: "PH", name: "Filipinas", dial: "63", lang: "en" },
  { code: "JP", name: "Japão", dial: "81", lang: "ja" },
  { code: "KR", name: "Coreia do Sul", dial: "82", lang: "ko" },
  { code: "CN", name: "China", dial: "86", lang: "zh" },
  { code: "HK", name: "Hong Kong", dial: "852", lang: "en" },
  { code: "TW", name: "Taiwan", dial: "886", lang: "zh" },
];

export function getCountry(code: string): Country {
  return COUNTRIES.find((c) => c.code === code) ?? COUNTRIES[0];
}
